// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _require(_webApiKey, 'ADMIN_WEB_FIREBASE_WEB_API_KEY'),
        appId: _require(_webAppId, 'ADMIN_WEB_FIREBASE_WEB_APP_ID'),
        messagingSenderId:
            _require(_messagingSenderId, 'ADMIN_WEB_FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _require(_projectId, 'ADMIN_WEB_FIREBASE_PROJECT_ID'),
        authDomain: _require(_webAuthDomain, 'ADMIN_WEB_FIREBASE_WEB_AUTH_DOMAIN'),
        storageBucket: _require(_storageBucket, 'ADMIN_WEB_FIREBASE_STORAGE_BUCKET'),
        measurementId:
            _optional(_webMeasurementId, 'ADMIN_WEB_FIREBASE_WEB_MEASUREMENT_ID'),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _require(_androidApiKey, 'ADMIN_WEB_FIREBASE_ANDROID_API_KEY'),
        appId: _require(_androidAppId, 'ADMIN_WEB_FIREBASE_ANDROID_APP_ID'),
        messagingSenderId:
            _require(_messagingSenderId, 'ADMIN_WEB_FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _require(_projectId, 'ADMIN_WEB_FIREBASE_PROJECT_ID'),
        storageBucket: _require(_storageBucket, 'ADMIN_WEB_FIREBASE_STORAGE_BUCKET'),
      );

  static const String _projectId =
      String.fromEnvironment('ADMIN_WEB_FIREBASE_PROJECT_ID', defaultValue: '');
  static const String _storageBucket =
      String.fromEnvironment('ADMIN_WEB_FIREBASE_STORAGE_BUCKET', defaultValue: '');
  static const String _messagingSenderId =
      String.fromEnvironment('ADMIN_WEB_FIREBASE_MESSAGING_SENDER_ID', defaultValue: '');

  static const String _webApiKey =
      String.fromEnvironment('ADMIN_WEB_FIREBASE_WEB_API_KEY', defaultValue: '');
  static const String _webAppId =
      String.fromEnvironment('ADMIN_WEB_FIREBASE_WEB_APP_ID', defaultValue: '');
  static const String _webAuthDomain =
      String.fromEnvironment('ADMIN_WEB_FIREBASE_WEB_AUTH_DOMAIN', defaultValue: '');
  static const String _webMeasurementId =
      String.fromEnvironment('ADMIN_WEB_FIREBASE_WEB_MEASUREMENT_ID', defaultValue: '');

  static const String _androidApiKey =
      String.fromEnvironment('ADMIN_WEB_FIREBASE_ANDROID_API_KEY', defaultValue: '');
  static const String _androidAppId =
      String.fromEnvironment('ADMIN_WEB_FIREBASE_ANDROID_APP_ID', defaultValue: '');

  static String _require(String value, String name) {
    if (value.isEmpty) {
      throw StateError('Missing Firebase configuration for $name. '
          'Provide it with --dart-define or --dart-define-from-file.');
    }
    return value;
  }

  static String? _optional(String value, String _) {
    if (value.isEmpty) {
      return null;
    }
    return value;
  }
}
