name: admin_web
description: "UPS Admin Panel - Administrative interface for UPS management system."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  provider: ^6.1.5+1
  go_router: ^16.2.1
  font_awesome_flutter: ^10.10.0
  data_table_2: ^2.5.15
  intl: ^0.20.2
  google_fonts: ^6.2.1
  file_picker: ^8.0.6
  url_launcher: ^6.3.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
